name: Tests

on: push

jobs:
  uni-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: 3.13.9
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter test test/unit -r expanded
      - run: flutter test test/widget -r expanded
